name: sara_flutter
description: "SARA - Smart Absher Response Assistant for Saudi Government Services"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.7
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  
  # Networking
  dio: ^5.7.0
  http: ^1.2.2
  pretty_dio_logger: ^1.4.0
  
  # Audio
  flutter_sound: ^9.16.3
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  
  # WebSocket for voice chat
  web_socket_channel: ^3.0.0
  
  # Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  
  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  
  # Markdown
  flutter_markdown: ^0.7.3+1
  markdown: ^7.2.2
  
  # JSON & Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
